services:
  organizations-postgres:
    image: postgres:16
    container_name: organizations-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - organizations-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    env_file:
      - ./.env

  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    container_name: organizations-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:minioadmin}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - organizations-minio-data:/data
    restart: unless-stopped
    env_file:
      - ./.env

  app:
    build: .
    container_name: organizations-service
    depends_on:
      organizations-postgres:
        condition: service_healthy
      - minio
    ports:
      - "8000:8080"
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      MINIO_URL: http://minio:9000

volumes:
  organizations-postgres-data:
  organizations-minio-data:
